UPPERLETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
LOWERLETTERS = UPPERLETTERS.lower()
NUMS = '0123456789'
SPECIALS = '!"#$%&\'()*+,-./:;<=>?@[\\]^_{|}~'
SPACE = ' '
TAB = '\t'
NEW_LINE = '\n'

LETTERS_AND_SPACE = UPPERLETTERS + LOWERLETTERS + SPACE + TAB + NEW_LINE
LETTERS = UPPERLETTERS + LOWERLETTERS + NUMS + SPECIALS + SPACE + TAB

ETAOIN_ALL = ' etaoinshrdlcumwfgypbvkjxqzSCAPBDRMIETFHLGWONUVJKQYZX!"#$%&\'()*+,-./0123456789:;<=>?@[\\]^_{|}~'
ETAOIN = ' ETAOINSHRDLCUMWFGYPBVKJXQZ'
