UPPERLETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
LOWERLETTERS = UPPERLETTERS.lower()

LETTERS_AND_SPACE = UPPERLETTERS + LOWERLETTERS + ' \t\n'
LETTERS = UPPERLETTERS + LOWERLETTERS + '!"#$%&\'()*+,-./0123456789:;<=>?@[\\]^_{|}~ '

ETAOIN_ALL = ' etaoinshrdlcumwfgypbvkjxqzSCAPBDRMIETFHLGWONUVJKQYZX!"#$%&\'()*+,-./0123456789:;<=>?@[\\]^_{|}~'
ETAOIN = ' ETAOINSHRDLCUMWFGYPBVKJXQZ'